[package]
name = "antigen"
version = "0.1.0"
authors = ["Amit Upadhyay <upadhyay@gmail.com>"]
edition = "2018"

[dependencies]
ftd = "0.1.0"


[dev-dependencies]
rusty-hook = "0.11.2"
fbt-lib = "0.1.5"
